### ISSUE TITLE
Manifest issues blocking GA release

### ISSUE THREAD

**Issue by nrc** [pingcap-incubator/tiup#255]
This is an issue to track what is left to do before we launch. Please add stuff!

cc @lonng @AstroProfundis @july2993 @lucklove 

- [x] Check we are doing all required validation of signatures and hashes @nrc (#265)
- [ ] Manual test of all commands including in tiup-cluster (expand this item)
- [ ] self-update #257 (need more test)
- [x] implement support for nightly versions @AstroProfundis @july2993 (#261, #264)
- [ ] check forward compatibility (a 0.1.1 spec version should cause an error which informs the user to update)
- [ ] ensure we can do the daily timestamp/snapshot updates and start a cron job to do it (or merge this with the nightly job) @lucklove 
- [ ] ensure generating nightlies causes all manifests to update properly
- [ ] get some beta testing!
- [x] tiup list for v1 @lucklove (#258)
- [ ] ensure the generated manifest include tiup itself @AstroProfundis 
- [x] refactor the `tiup mirror` to adapt the v1 manifest. @lonng  (#263)
- [x] check other components in tiup works with v1 too, guess mainly `playground` (#269)
- [ ] Fix `TestWithMigrate` @july2993 

If we can't get to the server side stuff, then we can check the expiry of timestamp/snapshot to a month instead of a day to give ourselves time to fix it and then use a shorter expiry

**Comment by july2993** [comment]
maybe one more:
ensure the generated manifest include tiup itself

**Comment by nrc** [comment]
Regarding beta testing, are we going to be able to ship this to some users a bit early (tomorrow?) to get it some real world testing? Or at least ask some PingCAP folk to take a look?
